-- No-op migration.
-- This file previously attempted to rename an index before the table existed,
-- causing P3006/P1014 in shadow DB during `prisma migrate dev`.
-- Kept intentionally empty to preserve migration ordering.
